import sys, os, logging

# Create secret key so we can use sessions
SECRET_KEY = '$SECRET_KEY'

# Flask settings
FLASK_SERVER_HOST = '0.0.0.0'
FLASK_SERVER_PORT = 5000
FLASK_API_URL_PREFIX = '/api/v1'
FLASK_DEBUG = False
DEBUG = False
PREFERRED_URL_SCHEME = 'https'

# E-mail configuration
MAIL_SERVER = '$EMAIL_SERVER'
MAIL_PORT = '$EMAIL_PORT'
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = '$EMAIL_USERNAME'
MAIL_PASSWORD = '$EMAIL_PASSWORD'
ADMINS = ['$ADMIN_EMAIL']

# Logging configuration
LOG_LEVEL = logging.INFO
LOG_FILENAME = 'activity.log'
LOG_MAXBYTES = 1024
LOG_BACKUPS = 2

# Portal database
SQLALCHEMY_DATABASE_HOST = '$DATABASE_HOST'
SQLALCHEMY_DATABASE_PORT = '$DATABASE_PORT'
SQLALCHEMY_DATABASE_USER = '$DATABASE_USER'
SQLALCHEMY_DATABASE_PASS = '$DATABASE_PSWD'
SQLALCHEMY_DATABASE_NAME = '$DATABASE_NAME'
SQLALCHEMY_POOL_RECYCLE = 110
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Tracking database (powered by Matomo)
MATOMO_DATABASE_USER = '$DATABASE_USER_TRACKING'
MATOMO_DATABASE_PASS = '$DATABASE_PSWD_TRACKING'
MATOMO_DATABASE_HOST = '$DATABASE_HOST_TRACKING'
MATOMO_DATABASE_PORT = '$DATABASE_PORT_TRACKING'
MATOMO_DATABASE_NAME = '$DATABASE_NAME_TRACKING'

SQLALCHEMY_DATABASE_URI = 'mysql+mysqlconnector://' + SQLALCHEMY_DATABASE_USER + ':' + SQLALCHEMY_DATABASE_PASS + '@' + SQLALCHEMY_DATABASE_HOST + ':' + SQLALCHEMY_DATABASE_PORT + '/' + SQLALCHEMY_DATABASE_NAME
SQLALCHEMY_BINDS = {
    'portal': SQLALCHEMY_DATABASE_URI,
    'matomo': 'mysql+mysqlconnector://' + MATOMO_DATABASE_USER + ':' + MATOMO_DATABASE_PASS + '@' + MATOMO_DATABASE_HOST + ':' + MATOMO_DATABASE_PORT + '/' + MATOMO_DATABASE_NAME,
}

# Microsoft AD B2C setup
MICROSOFT_TENANT_ID = '$AZUREADB2C_TENANT_ID'
MICROSOFT_CLIENT_ID = '$AZUREADB2C_CLIENT_ID'
MICROSOFT_CLIENT_SECRET = r'$AZUREADB2C_CLIENT_SECRET'
MICROSOFT_POLICY_NAME = '$AZUREADB2C_POLICY_NAME'
MICROSOFT_POLICY_NAME_PWD_RESET = '$AZUREADB2C_POLICY_NAME_PWD_RESET'

# Tracking URLs
MATOMO_ADMIN_TOKEN = '$MATOMO_ADMIN_TOKEN'
MATOMO_URL = 'TRACKING_PORTAL_URL'              # used by widgets
MATOMO_API_URL = 'TRACKING_API_URL'             # used by API requests
MATOMO_TRACKING_URL = 'TRACKING_FRONTEND_URL'   # used in tracking code
