import enum

WEBSITE_CURRENCY = [
    ('CZK', "[Kč] Czech koruna"),
    ('EUR', "[€] Euro"),
    ('USD', "[$] US dollar"),
    ('GBP', "[£] British pound"),
    ('CHF', "[Fr] Swiss franc"),
    ('AFN', "[؋] Afghan afghani"),
    ('ALL', "[L] Albanian lek"),
    ('DZD', "[د.ج] Algerian dinar"),
    ('AOA', "[Kz] Angolan kwanza"),
    ('ARS', "[$] Argentine peso"),
    ('AMD', "[դր.] Armenian dram"),
    ('AWG', "[ƒ] Aruban florin"),
    ('AUD', "[$] Australian dollar"),
    ('AZN', "[m] Azerbaijani manat"),
    ('BSD', "[$] Bahamian dollar"),
    ('BHD', "[.د.ب] Bahraini dinar"),
    ('BDT', "[৳] Bangladeshi taka"),
    ('BBD', "[$] Barbadian dollar"),
    ('BYN', "[Br] Belarusian ruble"),
    ('BZD', "[$] Belize dollar"),
    ('BMD', "[$] Bermudian dollar"),
    ('BTN', "[Nu.] Bhutanese ngultrum"),
    ('BOB', "[Bs.] Bolivian boliviano"),
    ('BAM', "[KM] Bosnia Herzegovina mark"),
    ('BWP', "[P] Botswana pula"),
    ('BRL', "[R$] Brazilian real"),
    ('BND', "[$] Brunei dollar"),
    ('BGN', "[лв] Bulgarian lev"),
    ('BIF', "[Fr] Burundian franc"),
    ('KHR', "[៛] Cambodian riel"),
    ('CAD', "[$] Canadian dollar"),
    ('CVE', "[$] Cape Verdean escudo"),
    ('KYD', "[$] Cayman Islands dollar"),
    ('XAF', "[Fr] Central African CFA franc"),
    ('CLP', "[$] Chilean peso"),
    ('CNY', "[元] Chinese yuan"),
    ('COP', "[$] Colombian peso"),
    ('KMF', "[Fr] Comorian franc"),
    ('CDF', "[Fr] Congolese franc"),
    ('CRC', "[₡] Costa Rican colón"),
    ('HRK', "[kn] Croatian kuna"),
    ('XPF', "[F] CFP franc"),
    ('CUC', "[$] Cuban convertible peso"),
    ('CUP', "[$] Cuban peso"),
    ('DKK', "[kr] Danish krone"),
    ('DJF', "[Fr] Djiboutian franc"),
    ('DOP', "[$] Dominican peso"),
    ('XCD', "[$] East Caribbean dollar"),
    ('EGP', "[ج.م] Egyptian pound"),
    ('ERN', "[Nfk] Eritrean nakfa"),
    ('ETB', "[Br] Ethiopian birr"),
    ('FKP', "[£] Falkland Islands pound"),
    ('FJD', "[$] Fijian dollar"),
    ('GMD', "[D] Gambian dalasi"),
    ('GEL', "[ლ] Georgian lari"),
    ('GHS', "[₵] Ghanaian cedi"),
    ('GIP', "[£] Gibraltar pound"),
    ('GTQ', "[Q] Guatemalan quetzal"),
    ('GNF', "[Fr] Guinean franc"),
    ('GYD', "[$] Guyanese dollar"),
    ('HTG', "[G] Haitian gourde"),
    ('HNL', "[L] Honduran lempira"),
    ('HKD', "[$] Hong Kong dollar"),
    ('HUF', "[Ft] Hungarian forint"),
    ('ISK', "[kr] Icelandic króna"),
    ('INR', "[‎₹] Indian rupee"),
    ('IDR', "[Rp] Indonesian rupiah"),
    ('IRR', "[﷼] Iranian rial"),
    ('IQD', "[ع.د] Iraqi dinar"),
    ('ILS', "[₪] Israeli new shekel"),
    ('JMD', "[$] Jamaican dollar"),
    ('JPY', "[¥] Japanese yen"),
    ('JOD', "[د.ا] Jordanian dinar"),
    ('KZT', "[₸] Kazakhstani tenge"),
    ('KES', "[Sh] Kenyan shilling"),
    ('KWD', "[د.ك] Kuwaiti dinar"),
    ('KGS', "[лв] Kyrgyzstani som"),
    ('LAK', "[₭] Lao kip"),
    ('LBP', "[ل.ل] Lebanese pound"),
    ('LSL', "[L] Lesotho loti"),
    ('LRD', "[$] Liberian dollar"),
    ('LYD', "[ل.د] Libyan dinar"),
    ('MOP', "[P] Macanese pataca"),
    ('MKD', "[ден] Macedonian denar"),
    ('MGA', "[Ar] Malagasy ariary"),
    ('MWK', "[MK] Malawian kwacha"),
    ('MYR', "[RM] Malaysian ringgit"),
    ('MVR', "[ރ.] Maldivian rufiyaa"),
    ('MRU', "[UM] Mauritanian ouguiya"),
    ('MUR', "[₨] Mauritian rupee"),
    ('MXN', "[$] Mexican peso"),
    ('MDL', "[L] Moldovan leu"),
    ('MNT', "[₮] Mongolian tögrög"),
    ('MAD', "[د.م.] Moroccan dirham"),
    ('MZN', "[MTn] Mozambican metical"),
    ('MMK', "[K] Myanma kyat"),
    ('NAD', "[$] Namibian dollar"),
    ('NPR', "[₨] Nepalese rupee"),
    ('ANG', "[ƒ] Netherlands Antillean guilder"),
    ('TWD', "[$] New Taiwan dollar"),
    ('NZD', "[$] New Zealand dollar"),
    ('NIO', "[C$] Nicaraguan córdoba"),
    ('NGN', "[₦] Nigerian naira"),
    ('KPW', "[₩] North Korean won"),
    ('NOK', "[kr] Norwegian krone"),
    ('OMR', "[ر.ع.] Omani rial"),
    ('PKR', "[₨] Pakistani rupee"),
    ('PAB', "[B/.] Panamanian balboa"),
    ('PGK', "[K] Papua New Guinean kina"),
    ('PYG', "[₲] Paraguayan guaraní"),
    ('PEN', "[S/.] Peruvian nuevo sol"),
    ('PHP', "[₱] Philippine peso"),
    ('PLN', "[zł] Polish złoty"),
    ('QAR', "[ر.ق] Qatari riyal"),
    ('RON', "[L] Romanian leu"),
    ('RUB', "[руб.] Russian ruble"),
    ('RWF', "[Fr] Rwandan franc"),
    ('SHP', "[£] Saint Helena pound"),
    ('SSP', "[£] South Sudanese pound"),
    ('WST', "[T] Samoan tala"),
    ('STN', "[Db] São Tomé and Príncipe dobra"),
    ('SAR', "[ر.س] Saudi riyal"),
    ('RSD', "[дин. or din.] Serbian dinar"),
    ('SCR', "[₨] Seychellois rupee"),
    ('SLL', "[Le] Sierra Leonean leone"),
    ('SGD', "[$] Singapore dollar"),
    ('SBD', "[$] Solomon Islands dollar"),
    ('SOS', "[Sh] Somali shilling"),
    ('ZAR', "[R] South African rand"),
    ('KRW', "[₩] South Korean won"),
    ('LKR', "[Rs] Sri Lankan rupee"),
    ('SDG', "[جنيه سوداني] Sudanese pound"),
    ('SRD', "[$] Surinamese dollar"),
    ('SZL', "[L] Swazi lilangeni"),
    ('SEK', "[kr] Swedish krona"),
    ('SYP', "[ل.س] Syrian pound"),
    ('TJS', "[ЅМ] Tajikistani somoni"),
    ('TZS', "[Sh] Tanzanian shilling"),
    ('THB', "[฿] Thai baht"),
    ('TOP', "[T$] Tongan paʻanga"),
    ('TTD', "[$] Trinidad and Tobago dollar"),
    ('TND', "[د.ت] Tunisian dinar"),
    ('TRY', "[TL] Turkish lira"),
    ('TMT', "[m] Turkmenistani manat"),
    ('UGX', "[Sh] Ugandan shilling"),
    ('UAH', "[₴] Ukrainian hryvnia"),
    ('AED', "[د.إ] United Arab Emirates dirham"),
    ('UYU', "[$] Uruguayan peso"),
    ('UZS', "[лв] Uzbekistani som"),
    ('VUV', "[Vt] Vanuatu vatu"),
    ('VEF', "[Bs F] Venezuelan bolívar"),
    ('VND', "[₫] Vietnamese đồng"),
    ('XOF', "[Fr] West African CFA franc"),
    ('YER', "[﷼] Yemeni rial"),
    ('ZMW', "[ZK] Zambian kwacha"),
]

WEBSITE_TIMEZONE = [
    ('Europe/Prague', "Czechia"),
    ('Europe/Tirane', "Albania"),
    ('Europe/Andorra', "Andorra"),
    ('Europe/Vienna', "Austria"),
    ('Europe/Minsk', "Belarus"),
    ('Europe/Brussels', "Belgium"),
    ('Europe/Sarajevo', "Bosnia&amp;Herzegovina"),
    ('Europe/Sofia', "Bulgaria"),
    ('Europe/Zagreb', "Croatia"),
    ('Asia/Famagusta', "Cyprus-Famagusta"),
    ('Asia/Nicosia', "Cyprus-Nicosia"),
    ('Europe/Copenhagen', "Denmark"),
    ('Europe/Tallinn', "Estonia"),
    ('Atlantic/Faroe', "FaroeIslands"),
    ('Europe/Helsinki', "Finland"),
    ('Europe/Paris', "France"),
    ('Europe/Berlin', "Germany-Berlin"),
    ('Europe/Busingen', "Germany-Busingen"),
    ('Europe/Gibraltar', "Gibraltar"),
    ('Europe/Athens', "Greece"),
    ('Europe/Guernsey', "Guernsey"),
    ('Europe/Budapest', "Hungary"),
    ('Atlantic/Reykjavik', "Iceland"),
    ('Europe/Dublin', "Ireland"),
    ('Europe/Isle_of_Man', "IsleofMan"),
    ('Europe/Rome', "Italy"),
    ('Europe/Jersey', "Jersey"),
    ('Europe/Riga', "Latvia"),
    ('Europe/Vaduz', "Liechtenstein"),
    ('Europe/Vilnius', "Lithuania"),
    ('Europe/Luxembourg', "Luxembourg"),
    ('Europe/Skopje', "Macedonia"),
    ('Europe/Malta', "Malta"),
    ('Europe/Chisinau', "Moldova"),
    ('Europe/Monaco', "Monaco"),
    ('Europe/Podgorica', "Montenegro"),
    ('Europe/Amsterdam', "Netherlands"),
    ('Europe/Oslo', "Norway"),
    ('Europe/Warsaw', "Poland"),
    ('Atlantic/Azores', "Portugal-Azores"),
    ('Europe/Lisbon', "Portugal-Lisbon"),
    ('Atlantic/Madeira', "Portugal-Madeira"),
    ('Europe/Bucharest', "Romania"),
    ('Asia/Anadyr', "Russia-Anadyr"),
    ('Europe/Astrakhan', "Russia-Astrakhan"),
    ('Asia/Barnaul', "Russia-Barnaul"),
    ('Asia/Chita', "Russia-Chita"),
    ('Asia/Irkutsk', "Russia-Irkutsk"),
    ('Europe/Kaliningrad', "Russia-Kaliningrad"),
    ('Asia/Kamchatka', "Russia-Kamchatka"),
    ('Asia/Khandyga', "Russia-Khandyga"),
    ('Europe/Kirov', "Russia-Kirov"),
    ('Asia/Krasnoyarsk', "Russia-Krasnoyarsk"),
    ('Asia/Magadan', "Russia-Magadan"),
    ('Europe/Moscow', "Russia-Moscow"),
    ('Asia/Novokuznetsk', "Russia-Novokuznetsk"),
    ('Asia/Novosibirsk', "Russia-Novosibirsk"),
    ('Asia/Omsk', "Russia-Omsk"),
    ('Asia/Sakhalin', "Russia-Sakhalin"),
    ('Europe/Samara', "Russia-Samara"),
    ('Europe/Saratov', "Russia-Saratov"),
    ('Europe/Simferopol', "Russia-Simferopol"),
    ('Asia/Srednekolymsk', "Russia-Srednekolymsk"),
    ('Asia/Tomsk', "Russia-Tomsk"),
    ('Europe/Ulyanovsk', "Russia-Ulyanovsk"),
    ('Asia/Ust-Nera', "Russia-Ust-Nera"),
    ('Asia/Vladivostok', "Russia-Vladivostok"),
    ('Europe/Volgograd', "Russia-Volgograd"),
    ('Asia/Yakutsk', "Russia-Yakutsk"),
    ('Asia/Yekaterinburg', "Russia-Yekaterinburg"),
    ('Europe/San_Marino', "SanMarino"),
    ('Europe/Belgrade', "Serbia"),
    ('Europe/Bratislava', "Slovakia"),
    ('Europe/Ljubljana', "Slovenia"),
    ('Atlantic/Canary', "Spain-Canary"),
    ('Africa/Ceuta', "Spain-Ceuta"),
    ('Europe/Madrid', "Spain-Madrid"),
    ('Arctic/Longyearbyen', "Svalbard&amp;JanMayen"),
    ('Europe/Stockholm', "Sweden"),
    ('Europe/Zurich', "Switzerland"),
    ('Europe/Istanbul', "Turkey"),
    ('Europe/Kiev', "Ukraine-Kiev"),
    ('Europe/Uzhgorod', "Ukraine-Uzhhorod"),
    ('Europe/Zaporozhye', "Ukraine-Zaporozhye"),
    ('Europe/London', "UnitedKingdom"),
    ('Europe/Vatican', "VaticanCity"),
    ('Europe/Mariehamn', "ÅlandIslands"),
    # ('Africa/Algiers', "Algeria"),
    # ('Africa/Luanda', "Angola"),
    # ('Africa/Porto-Novo', "Benin"),
    # ('Africa/Gaborone', "Botswana"),
    # ('Africa/Ouagadougou', "BurkinaFaso"),
    # ('Africa/Bujumbura', "Burundi"),
    # ('Africa/Douala', "Cameroon"),
    # ('Atlantic/Cape_Verde', "CapeVerde"),
    # ('Africa/Bangui', "CentralAfricanRepublic"),
    # ('Africa/Ndjamena', "Chad"),
    # ('Indian/Comoro', "Comoros"),
    # ('Africa/Brazzaville', "Congo-Brazzaville"),
    # ('Africa/Kinshasa', "Congo-Kinshasa-Kinshasa"),
    # ('Africa/Lubumbashi', "Congo-Kinshasa-Lubumbashi"),
    # ('Africa/Abidjan', "Côted’Ivoire"),
    # ('Africa/Djibouti', "Djibouti"),
    # ('Africa/Cairo', "Egypt"),
    # ('Africa/Malabo', "EquatorialGuinea"),
    # ('Africa/Asmara', "Eritrea"),
    # ('Africa/Addis_Ababa', "Ethiopia"),
    # ('Africa/Libreville', "Gabon"),
    # ('Africa/Banjul', "Gambia"),
    # ('Africa/Accra', "Ghana"),
    # ('Africa/Conakry', "Guinea"),
    # ('Africa/Bissau', "Guinea-Bissau"),
    # ('Africa/Nairobi', "Kenya"),
    # ('Africa/Maseru', "Lesotho"),
    # ('Africa/Monrovia', "Liberia"),
    # ('Africa/Tripoli', "Libya"),
    # ('Indian/Antananarivo', "Madagascar"),
    # ('Africa/Blantyre', "Malawi"),
    # ('Africa/Bamako', "Mali"),
    # ('Africa/Nouakchott', "Mauritania"),
    # ('Indian/Mauritius', "Mauritius"),
    # ('Indian/Mayotte', "Mayotte"),
    # ('Africa/Casablanca', "Morocco"),
    # ('Africa/Maputo', "Mozambique"),
    # ('Africa/Windhoek', "Namibia"),
    # ('Africa/Niamey', "Niger"),
    # ('Africa/Lagos', "Nigeria"),
    # ('Africa/Kigali', "Rwanda"),
    # ('Indian/Reunion', "Réunion"),
    # ('Africa/Dakar', "Senegal"),
    # ('Indian/Mahe', "Seychelles"),
    # ('Africa/Freetown', "SierraLeone"),
    # ('Africa/Mogadishu', "Somalia"),
    # ('Africa/Johannesburg', "SouthAfrica"),
    # ('Africa/Juba', "SouthSudan"),
    # ('Atlantic/St_Helena', "St.Helena"),
    # ('Africa/Khartoum', "Sudan"),
    # ('Africa/Mbabane', "Swaziland"),
    # ('Africa/Sao_Tome', "SãoTomé&amp;Príncipe"),
    # ('Africa/Dar_es_Salaam', "Tanzania"),
    # ('Africa/Lome', "Togo"),
    # ('Africa/Tunis', "Tunisia"),
    # ('Africa/Kampala', "Uganda"),
    # ('Africa/El_Aaiun', "WesternSahara"),
    # ('Africa/Lusaka', "Zambia"),
    # ('Africa/Harare', "Zimbabwe"),
    # ('Antarctica/Casey', "Antarctica-Casey"),
    # ('Antarctica/Davis', "Antarctica-Davis"),
    # ('Antarctica/DumontDUrville', "Antarctica-Dumont-Urville"),
    # ('Antarctica/Mawson', "Antarctica-Mawson"),
    # ('Antarctica/McMurdo', "Antarctica-McMurdo"),
    # ('Antarctica/Palmer', "Antarctica-Palmer"),
    # ('Antarctica/Rothera', "Antarctica-Rothera"),
    # ('Antarctica/Syowa', "Antarctica-Syowa"),
    # ('Antarctica/Troll', "Antarctica-Troll"),
    # ('Antarctica/Vostok', "Antarctica-Vostok"),
    # ('Indian/Kerguelen', "FrenchSouthernTerritories"),
    # ('Atlantic/South_Georgia', "SouthGeorgia"),
    # ('Asia/Kabul', "Afghanistan"),
    # ('Asia/Yerevan', "Armenia"),
    # ('Asia/Baku', "Azerbaijan"),
    # ('Asia/Bahrain', "Bahrain"),
    # ('Asia/Dhaka', "Bangladesh"),
    # ('Asia/Thimphu', "Bhutan"),
    # ('Indian/Chagos', "BritishIndianOceanTerritory"),
    # ('Asia/Brunei', "Brunei"),
    # ('Asia/Phnom_Penh', "Cambodia"),
    # ('Asia/Shanghai', "China-Shanghai"),
    # ('Asia/Urumqi', "China-Urumqi"),
    # ('Indian/Christmas', "ChristmasIsland"),
    # ('Indian/Cocos', "Cocos(Keeling)Islands"),
    # ('Asia/Tbilisi', "Georgia"),
    # ('Asia/Hong_Kong', "HongKongSARChina"),
    # ('Asia/Kolkata', "India"),
    # ('Asia/Jakarta', "Indonesia-Jakarta"),
    # ('Asia/Jayapura', "Indonesia-Jayapura"),
    # ('Asia/Makassar', "Indonesia-Makassar"),
    # ('Asia/Pontianak', "Indonesia-Pontianak"),
    # ('Asia/Tehran', "Iran"),
    # ('Asia/Baghdad', "Iraq"),
    # ('Asia/Jerusalem', "Israel"),
    # ('Asia/Tokyo', "Japan"),
    # ('Asia/Amman', "Jordan"),
    # ('Asia/Almaty', "Kazakhstan-Almaty"),
    # ('Asia/Aqtau', "Kazakhstan-Aqtau"),
    # ('Asia/Aqtobe', "Kazakhstan-Aqtobe"),
    # ('Asia/Atyrau', "Kazakhstan-Atyrau"),
    # ('Asia/Oral', "Kazakhstan-Oral"),
    # ('Asia/Qyzylorda', "Kazakhstan-Qyzylorda"),
    # ('Asia/Kuwait', "Kuwait"),
    # ('Asia/Bishkek', "Kyrgyzstan"),
    # ('Asia/Vientiane', "Laos"),
    # ('Asia/Beirut', "Lebanon"),
    # ('Asia/Macau', "MacauSARChina"),
    # ('Asia/Kuala_Lumpur', "Malaysia-KualaLumpur"),
    # ('Asia/Kuching', "Malaysia-Kuching"),
    # ('Indian/Maldives', "Maldives"),
    # ('Asia/Choibalsan', "Mongolia-Choibalsan"),
    # ('Asia/Hovd', "Mongolia-Hovd"),
    # ('Asia/Ulaanbaatar', "Mongolia-Ulaanbaatar"),
    # ('Asia/Yangon', "Myanmar(Burma)"),
    # ('Asia/Kathmandu', "Nepal"),
    # ('Asia/Pyongyang', "NorthKorea"),
    # ('Asia/Muscat', "Oman"),
    # ('Asia/Karachi', "Pakistan"),
    # ('Asia/Gaza', "PalestinianTerritories-Gaza"),
    # ('Asia/Hebron', "PalestinianTerritories-Hebron"),
    # ('Asia/Manila', "Philippines"),
    # ('Asia/Qatar', "Qatar"),
    # ('Asia/Riyadh', "SaudiArabia"),
    # ('Asia/Singapore', "Singapore"),
    # ('Asia/Seoul', "SouthKorea"),
    # ('Asia/Colombo', "SriLanka"),
    # ('Asia/Damascus', "Syria"),
    # ('Asia/Taipei', "Taiwan"),
    # ('Asia/Dushanbe', "Tajikistan"),
    # ('Asia/Bangkok', "Thailand"),
    # ('Asia/Dili', "Timor-Leste"),
    # ('Asia/Ashgabat', "Turkmenistan"),
    # ('Asia/Dubai', "UnitedArabEmirates"),
    # ('Asia/Samarkand', "Uzbekistan-Samarkand"),
    # ('Asia/Tashkent', "Uzbekistan-Tashkent"),
    # ('Asia/Ho_Chi_Minh', "Vietnam"),
    # ('Asia/Aden', "Yemen"),
    # ('America/Anguilla', "Anguilla"),
    # ('America/Antigua', "Antigua&amp;Barbuda"),
    # ('America/Aruba', "Aruba"),
    # ('America/Nassau', "Bahamas"),
    # ('America/Barbados', "Barbados"),
    # ('America/Belize', "Belize"),
    # ('Atlantic/Bermuda', "Bermuda"),
    # ('America/Tortola', "BritishVirginIslands"),
    # ('America/Kralendijk', "CaribbeanNetherlands"),
    # ('America/Cayman', "CaymanIslands"),
    # ('America/Costa_Rica', "CostaRica"),
    # ('America/Havana', "Cuba"),
    # ('America/Curacao', "Curaçao"),
    # ('America/Dominica', "Dominica"),
    # ('America/Santo_Domingo', "DominicanRepublic"),
    # ('America/El_Salvador', "ElSalvador"),
    # ('America/Grenada', "Grenada"),
    # ('America/Guadeloupe', "Guadeloupe"),
    # ('America/Guatemala', "Guatemala"),
    # ('America/Port-au-Prince', "Haiti"),
    # ('America/Tegucigalpa', "Honduras"),
    # ('America/Jamaica', "Jamaica"),
    # ('America/Martinique', "Martinique"),
    # ('America/Montserrat', "Montserrat"),
    # ('America/Managua', "Nicaragua"),
    # ('America/Panama', "Panama"),
    # ('America/Puerto_Rico', "PuertoRico"),
    # ('America/Lower_Princes', "SintMaarten"),
    # ('America/St_Barthelemy', "St.Barthélemy"),
    # ('America/St_Kitts', "St.Kitts&amp;Nevis"),
    # ('America/St_Lucia', "St.Lucia"),
    # ('America/Marigot', "St.Martin"),
    # ('America/St_Vincent', "St.Vincent&amp;Grenadines"),
    # ('America/Port_of_Spain', "Trinidad&amp;Tobago"),
    # ('America/Grand_Turk', "Turks&amp;CaicosIslands"),
    # ('America/St_Thomas', "U.S.VirginIslands"),
    # ('America/Atikokan', "Canada-Atikokan"),
    # ('America/Blanc-Sablon', "Canada-Blanc-Sablon"),
    # ('America/Cambridge_Bay', "Canada-CambridgeBay"),
    # ('America/Creston', "Canada-Creston"),
    # ('America/Dawson', "Canada-Dawson"),
    # ('America/Dawson_Creek', "Canada-DawsonCreek"),
    # ('America/Edmonton', "Canada-Edmonton"),
    # ('America/Fort_Nelson', "Canada-FortNelson"),
    # ('America/Glace_Bay', "Canada-GlaceBay"),
    # ('America/Goose_Bay', "Canada-GooseBay"),
    # ('America/Halifax', "Canada-Halifax"),
    # ('America/Inuvik', "Canada-Inuvik"),
    # ('America/Iqaluit', "Canada-Iqaluit"),
    # ('America/Moncton', "Canada-Moncton"),
    # ('America/Nipigon', "Canada-Nipigon"),
    # ('America/Pangnirtung', "Canada-Pangnirtung"),
    # ('America/Rainy_River', "Canada-RainyRiver"),
    # ('America/Rankin_Inlet', "Canada-RankinInlet"),
    # ('America/Regina', "Canada-Regina"),
    # ('America/Resolute', "Canada-Resolute"),
    # ('America/St_Johns', "Canada-St.John’s"),
    # ('America/Swift_Current', "Canada-SwiftCurrent"),
    # ('America/Thunder_Bay', "Canada-ThunderBay"),
    # ('America/Toronto', "Canada-Toronto"),
    # ('America/Vancouver', "Canada-Vancouver"),
    # ('America/Whitehorse', "Canada-Whitehorse"),
    # ('America/Winnipeg', "Canada-Winnipeg"),
    # ('America/Yellowknife', "Canada-Yellowknife"),
    # ('America/Danmarkshavn', "Greenland-Danmarkshavn"),
    # ('America/Scoresbysund', "Greenland-Ittoqqortoormiit"),
    # ('America/Godthab', "Greenland-Nuuk"),
    # ('America/Thule', "Greenland-Thule"),
    # ('America/Bahia_Banderas', "Mexico-BahiaBanderas"),
    # ('America/Cancun', "Mexico-Cancun"),
    # ('America/Chihuahua', "Mexico-Chihuahua"),
    # ('America/Hermosillo', "Mexico-Hermosillo"),
    # ('America/Matamoros', "Mexico-Matamoros"),
    # ('America/Mazatlan', "Mexico-Mazatlan"),
    # ('America/Merida', "Mexico-Merida"),
    # ('America/Mexico_City', "Mexico-MexicoCity"),
    # ('America/Monterrey', "Mexico-Monterrey"),
    # ('America/Ojinaga', "Mexico-Ojinaga"),
    # ('America/Tijuana', "Mexico-Tijuana"),
    # ('America/Miquelon', "St.Pierre&amp;Miquelon"),
    # ('America/Adak', "UnitedStates-Adak"),
    # ('America/Anchorage', "UnitedStates-Anchorage"),
    # ('America/North_Dakota/Beulah', "UnitedStates-NorthDakota"),
    # ('America/Boise', "UnitedStates-Boise-Center"),
    # ('America/North_Dakota/Center', "UnitedStates-NorthDakota"),
    # ('America/Chicago', "UnitedStates-Chicago"),
    # ('America/Denver', "UnitedStates-Denver"),
    # ('America/Detroit', "UnitedStates-Detroit"),
    # ('Pacific/Honolulu', "UnitedStates-Honolulu"),
    # ('America/Indiana/Indianapolis', "UnitedStates-"),
    # ('America/Juneau', "UnitedStates-Juneau"),
    # ('America/Indiana/Knox', "UnitedStates-Knox,Indiana"),
    # ('America/Los_Angeles', "UnitedStates-LosAngeles"),
    # ('America/Kentucky/Louisville', "UnitedStates-Louisville"),
    # ('America/Indiana/Marengo', "UnitedStates-Marengo,"),
    # ('America/Menominee', "UnitedStates-Menominee"),
    # ('America/Metlakatla', "UnitedStates-Metlakatla"),
    # ('America/Kentucky/Monticello', "UnitedStates-Kentucky"),
    # ('America/North_Dakota/New_Salem', "UnitedStates-NewSalem,NorthDakota"),
    # ('America/New_York', "UnitedStates-NewYork"),
    # ('America/Nome', "UnitedStates-Nome"),
    # ('America/Indiana/Petersburg', "UnitedStates-Indiana"),
    # ('America/Phoenix', "UnitedStates-Phoenix"),
    # ('America/Sitka', "UnitedStates-Sitka"),
    # ('America/Indiana/Tell_City', "UnitedStates-Tell,Indiana"),
    # ('America/Indiana/Vevay', "UnitedStates-Vevay,Indiana"),
    # ('America/Indiana/Vincennes', "UnitedStates-Indiana"),
    # ('America/Indiana/Winamac', "UnitedStates-Winamac,Indiana"),
    # ('America/Yakutat', "UnitedStates-Yakutat"),
    # ('Pacific/Pago_Pago', "AmericanSamoa"),
    # ('Australia/Adelaide', "Australia-Adelaide"),
    # ('Australia/Brisbane', "Australia-Brisbane"),
    # ('Australia/Broken_Hill', "Australia-BrokenHill"),
    # ('Australia/Currie', "Australia-Currie"),
    # ('Australia/Darwin', "Australia-Darwin"),
    # ('Australia/Eucla', "Australia-Eucla"),
    # ('Australia/Hobart', "Australia-Hobart"),
    # ('Australia/Lindeman', "Australia-Lindeman"),
    # ('Australia/Lord_Howe', "Australia-LordHowe"),
    # ('Antarctica/Macquarie', "Australia-Macquarie"),
    # ('Australia/Melbourne', "Australia-Melbourne"),
    # ('Australia/Perth', "Australia-Perth"),
    # ('Australia/Sydney', "Australia-Sydney"),
    # ('Pacific/Rarotonga', "CookIslands"),
    # ('Pacific/Fiji', "Fiji"),
    # ('Pacific/Gambier', "FrenchPolynesia-Gambier"),
    # ('Pacific/Marquesas', "FrenchPolynesia-Marquesas"),
    # ('Pacific/Tahiti', "FrenchPolynesia-Tahiti"),
    # ('Pacific/Guam', "Guam"),
    # ('Pacific/Enderbury', "Kiribati-Enderbury"),
    # ('Pacific/Kiritimati', "Kiribati-Kiritimati"),
    # ('Pacific/Tarawa', "Kiribati-Tarawa"),
    # ('Pacific/Kwajalein', "MarshallIslands-Kwajalein"),
    # ('Pacific/Majuro', "MarshallIslands-Majuro"),
    # ('Pacific/Chuuk', "Micronesia-Chuuk"),
    # ('Pacific/Kosrae', "Micronesia-Kosrae"),
    # ('Pacific/Pohnpei', "Micronesia-Pohnpei"),
    # ('Pacific/Nauru', "Nauru"),
    # ('Pacific/Noumea', "NewCaledonia"),
    # ('Pacific/Auckland', "NewZealand-Auckland"),
    # ('Pacific/Chatham', "NewZealand-Chatham"),
    # ('Pacific/Niue', "Niue"),
    # ('Pacific/Norfolk', "NorfolkIsland"),
    # ('Pacific/Saipan', "NorthernMarianaIslands"),
    # ('Pacific/Palau', "Palau"),
    # ('Pacific/Bougainville', "PapuaNewGuinea-Bougainville"),
    # ('Pacific/Port_Moresby', "PapuaNewGuinea-PortMoresby"),
    # ('Pacific/Pitcairn', "PitcairnIslands"),
    # ('Pacific/Apia', "Samoa"),
    # ('Pacific/Guadalcanal', "SolomonIslands"),
    # ('Pacific/Fakaofo', "Tokelau"),
    # ('Pacific/Tongatapu', "Tonga"),
    # ('Pacific/Funafuti', "Tuvalu"),
    # ('Pacific/Midway', "U.S.OutlyingIslands-Midway"),
    # ('Pacific/Wake', "U.S.OutlyingIslands-Wake"),
    # ('Pacific/Efate', "Vanuatu"),
    # ('Pacific/Wallis', "Wallis&amp;Futuna"),
    # ('America/Argentina/Buenos_Aires', "Argentina-BuenosAires"),
    # ('America/Argentina/Catamarca', "Argentina-Catamarca"),
    # ('America/Argentina/Cordoba', "Argentina-Cordoba"),
    # ('America/Argentina/Jujuy', "Argentina-Jujuy"),
    # ('America/Argentina/La_Rioja', "Argentina-LaRioja"),
    # ('America/Argentina/Mendoza', "Argentina-Mendoza"),
    # ('America/Argentina/Rio_Gallegos', "Argentina-RioGallegos"),
    # ('America/Argentina/Salta', "Argentina-Salta"),
    # ('America/Argentina/San_Juan', "Argentina-SanJuan"),
    # ('America/Argentina/San_Luis', "Argentina-SanLuis"),
    # ('America/Argentina/Tucuman', "Argentina-Tucuman"),
    # ('America/Argentina/Ushuaia', "Argentina-Ushuaia"),
    # ('America/La_Paz', "Bolivia"),
    # ('America/Araguaina', "Brazil-Araguaina"),
    # ('America/Bahia', "Brazil-Bahia"),
    # ('America/Belem', "Brazil-Belem"),
    # ('America/Boa_Vista', "Brazil-BoaVista"),
    # ('America/Campo_Grande', "Brazil-CampoGrande"),
    # ('America/Cuiaba', "Brazil-Cuiaba"),
    # ('America/Eirunepe', "Brazil-Eirunepe"),
    # ('America/Fortaleza', "Brazil-Fortaleza"),
    # ('America/Maceio', "Brazil-Maceio"),
    # ('America/Manaus', "Brazil-Manaus"),
    # ('America/Noronha', "Brazil-Noronha"),
    # ('America/Porto_Velho', "Brazil-PortoVelho"),
    # ('America/Recife', "Brazil-Recife"),
    # ('America/Rio_Branco', "Brazil-RioBranco"),
    # ('America/Santarem', "Brazil-Santarem"),
    # ('America/Sao_Paulo', "Brazil-SaoPaulo"),
    # ('Pacific/Easter', "Chile-Easter"),
    # ('America/Punta_Arenas', "Chile-PuntaArenas"),
    # ('America/Santiago', "Chile-Santiago"),
    # ('America/Bogota', "Colombia"),
    # ('Pacific/Galapagos', "Ecuador-Galapagos"),
    # ('America/Guayaquil', "Ecuador-Guayaquil"),
    # ('Atlantic/Stanley', "FalklandIslands"),
    # ('America/Cayenne', "FrenchGuiana"),
    # ('America/Guyana', "Guyana"),
    # ('America/Asuncion', "Paraguay"),
    # ('America/Lima', "Peru"),
    # ('America/Paramaribo', "Suriname"),
    # ('America/Montevideo', "Uruguay"),
    # ('America/Caracas', "Venezuela"),
    ('UTC-12', "UTC-12"),
    ('UTC-11.5', "UTC-11:30"),
    ('UTC-11', "UTC-11"),
    ('UTC-10.5', "UTC-10:30"),
    ('UTC-10', "UTC-10"),
    ('UTC-9.5', "UTC-9:30"),
    ('UTC-9', "UTC-9"),
    ('UTC-8.5', "UTC-8:30"),
    ('UTC-8', "UTC-8"),
    ('UTC-7.5', "UTC-7:30"),
    ('UTC-7', "UTC-7"),
    ('UTC-6.5', "UTC-6:30"),
    ('UTC-6', "UTC-6"),
    ('UTC-5.5', "UTC-5:30"),
    ('UTC-5', "UTC-5"),
    ('UTC-4.5', "UTC-4:30"),
    ('UTC-4', "UTC-4"),
    ('UTC-3.5', "UTC-3:30"),
    ('UTC-3', "UTC-3"),
    ('UTC-2.5', "UTC-2:30"),
    ('UTC-2', "UTC-2"),
    ('UTC-1.5', "UTC-1:30"),
    ('UTC-1', "UTC-1"),
    ('UTC-0.5', "UTC-0:30"),
    ('UTC', "UTC"),
    ('UTC+0.5', "UTC+0:30"),
    ('UTC+1', "UTC+1"),
    ('UTC+1.5', "UTC+1:30"),
    ('UTC+2', "UTC+2"),
    ('UTC+2.5', "UTC+2:30"),
    ('UTC+3', "UTC+3"),
    ('UTC+3.5', "UTC+3:30"),
    ('UTC+4', "UTC+4"),
    ('UTC+4.5', "UTC+4:30"),
    ('UTC+5', "UTC+5"),
    ('UTC+5.5', "UTC+5:30"),
    ('UTC+5.75', "UTC+5:45"),
    ('UTC+6', "UTC+6"),
    ('UTC+6.5', "UTC+6:30"),
    ('UTC+7', "UTC+7"),
    ('UTC+7.5', "UTC+7:30"),
    ('UTC+8', "UTC+8"),
    ('UTC+8.5', "UTC+8:30"),
    ('UTC+8.75', "UTC+8:45"),
    ('UTC+9', "UTC+9"),
    ('UTC+9.5', "UTC+9:30"),
    ('UTC+10', "UTC+10"),
    ('UTC+10.5', "UTC+10:30"),
    ('UTC+11', "UTC+11"),
    ('UTC+11.5', "UTC+11:30"),
    ('UTC+12', "UTC+12"),
    ('UTC+12.75', "UTC+12:45"),
    ('UTC+13', "UTC+13"),
    ('UTC+13.75', "UTC+13:45"),
    ('UTC+14', "UTC+14"),
]

HEATMAP_SAMPLE_LIMIT = (
    (1000, '1000'),
    (2000, '2000'),
    (5000, '5000'),
)

HEATMAP_SAMPLE_RATES = (
    (0.1, '0.1%'),
    (0.5, '0.5%'),
    (1.0, '1%'),
    (2.0, '2%'),
    (3.0, '3%'),
    (4.0, '4%'),
    (5.0, '5%'),
    (6.0, '6%'),
    (8.0, '8%'),
    (10.0, '10%'),
    (15.0, '15%'),
    (20.0, '20%'),
    (30.0, '30%'),
    (40.0, '40%'),
    (50.0, '50%'),
    (60.0, '60%'),
    (70.0, '70%'),
    (80.0, '80%'),
    (90.0, '90%'),
    (100.0, '100%'),
)

RULES = (
    ('url', 'URL'),
    ('path', 'Path'),
    ('urlparam', 'URL Parameter')
)

RULES_TYPE = (
    ('equals_exactly', 'equals exactly'),
    ('not_equals_exactly', 'not equals exactly'),
    ('equals_simple', 'equals simple'),
    ('not_equals_simple', 'not equals simple'),
    ('contains', 'contains'),
    ('not_contains', 'not contains'),
    ('starts_with', 'starts with'),
    ('not_starts_with', 'not starts with'),
    ('rexep', 'matches the regular expression'),
    ('not_rexep', 'not matches the regular expression'),
)

SESSION_RECORDING_SAMPLE_LIMIT = (
    (50, '50'),
    (100, '100'),
    (250, '250'),
    (500, '500'),
    (1000, '1000'),
    (2000, '2000'),
    (5000, '5000'),
)

SESSION_RECORDING_SAMPLE_RATE = (
    (0.1, '0.1%'),
    (0.5, '0.5%'),
    (1.0, '1%'),
    (2.0, '2%'),
    (3.0, '3%'),
    (4.0, '4%'),
    (5.0, '5%'),
    (6.0, '6%'),
    (8.0, '8%'),
    (10.0, '10%'),
    (15.0, '15%'),
    (20.0, '20%'),
    (30.0, '30%'),
    (40.0, '40%'),
    (50.0, '50%'),
    (60.0, '60%'),
    (70.0, '70%'),
    (80.0, '80%'),
    (90.0, '90%'),
    (100.0, '100%'),
)

SESSION_RECORDING_MIN_SESSION_TIME = (
    (0, '0 seconds'),
    (5, '5 seconds'),
    (10, '10 seconds'),
    (15, '15 seconds'),
    (20, '20 seconds'),
    (30, '30 seconds'),
    (45, '45 seconds'),
    (60, '60 seconds'),
    (90, '90 seconds'),
    (120, '120 seconds'),
)


DEVICE_TYPE = (
    (1, "pc"),
    (2, "smartphone"),
    (3, "notebook"),
    (4, "macbook"),
    (5, "macpc"),
    (6, "phone"),
)

LANGUAGES = (
    (1, "en"),
    (2, "cs"),
    (3, "sk"),
    (4, "de"),
    (5, "fr"),
    (6, "it"),
)

PARTNER_TYPE = (
    (1, "e-shop"),
    (2, "manufacturer"),
    (3, "entrepreneur"),
    (4, "marketing agency"),
    (5, "education"),
    (6, "media"),
    (7, "research and developement"),
    (8, "finance"),
    (9, "other"),
)

VISITOR_TYPE = (
    (1, "new"),
    (2, "returning"),
)

GEO_LOCATION_TYPE = (
    (1, "company address"),
    (2, "billing address"),
    (3, "brick and mortar"),
    (4, "subsidiary"),
    (5, "personal"),
    (6, "product placement"),
)

URL_FOR_ARGS = ('idSite', 'period', 'date',)

CONTENT_TYPE = (
    (1, "video"),
    (2, "news"),
    (3, "picture"),
    (4, "banner"),
)

MEDIA_TYPE = (
    (1, "picture"),
    (2, "youtube video"),
    (3, "site"),
)

media_types = ['picture', 'youtube video', 'site']

CONTACT_TYPE = (
    (1, "primary"),
    (2, "secondary"),
)

SITE_TYPE = (
    (1, "ecommerce"),
    (2, "site"),
)


URL_FOR_ARGS = ('idSite', 'period', 'date',)


CURRENCY = (
    (1, "czk"),
    (2, "eur"),
    (3, "usd"),
    (4, "gbp"),
)

PRODUCT_TRACKING_TYPE = (
    (1, 'purchase'),
    (2, 'refusal'),
    (3, 'in basket'),
    (4, 'out basket'),
    (5, 'view'),
    (6, 'search'),
)

ROLE_TYPE = (
    (1, 'admin'),
    (2, 'view'),
    (3, 'write'),
)

class WebsiteCurrency(enum.Enum):
    czk = 1
    eur = 2
    usd = 3
    gbp = 4


class Languages(enum.Enum):
    en = 1
    cs = 2
    sk = 3
    de = 4
    fr = 5
    it = 6


class RoleType(enum.Enum):
    admin = 1
    view = 2
    write = 3


class ContentType(enum.Enum):
    video = 1
    news = 2
    picture = 3
    banner = 4


class PartnerType(enum.Enum):
    distributor = 1
    manufacturer = 2


class MediaType(enum.Enum):
    picture = 1
    youtube_video = 2
    site = 3


class SiteType(enum.Enum):
    ecommerce = 1
    site = 2


class ProductTrackingRecordType(enum.Enum):
    purchase = 1
    refusal = 2
    in_basket = 3
    out_basket = 4
    view = 5
    search = 6


class VisitorType(enum.Enum):
    new = 1
    returning = 2


class ContactType(enum.Enum):
    primary = 1
    secondary = 2


class GeoLocationType(enum.Enum):
    company_address = 1
    billing_address = 2
    brick_and_mortar = 3
    subsidiary = 4
    personal = 5
    product_placement = 6


class DeviceType(enum.Enum):
    pc = 1
    smartphone = 2
    notebook = 3
    macbook = 4
    macpc = 5
    phone = 6


COUNTRY_CODES = [
    ('AF','Afghanistan'),
    ('AX','Åland Islands'),
    ('AL','Albania'),
    ('DZ','Algeria'),
    ('AS','American Samoa'),
    ('AD','Andorra'),
    ('AO','Angola'),
    ('AI','Anguilla'),
    ('AQ','Antarctica'),
    ('AG','Antigua and Barbuda'),
    ('AR','Argentina'),
    ('AM','Armenia'),
    ('AW','Aruba'),
    ('AU','Australia'),
    ('AT','Austria'),
    ('AZ','Azerbaijan'),
    ('BS','Bahamas'),
    ('BH','Bahrain'),
    ('BD','Bangladesh'),
    ('BB','Barbados'),
    ('BY','Belarus'),
    ('BE','Belgium'),
    ('BZ','Belize'),
    ('BJ','Benin'),
    ('BM','Bermuda'),
    ('BT','Bhutan'),
    ('BO','Bolivia (Plurinational State of)'),
    ('BQ','Bonaire, Sint Eustatius and Saba'),
    ('BA','Bosnia and Herzegovina'),
    ('BW','Botswana'),
    ('BV','Bouvet Island'),
    ('BR','Brazil'),
    ('IO','British Indian Ocean Territory'),
    ('BN','Brunei Darussalam'),
    ('BG','Bulgaria'),
    ('BF','Burkina Faso'),
    ('BI','Burundi'),
    ('CV','Cabo Verde'),
    ('KH','Cambodia'),
    ('CM','Cameroon'),
    ('CA','Canada'),
    ('KY','Cayman Islands'),
    ('CF','Central African Republic'),
    ('TD','Chad'),
    ('CL','Chile'),
    ('CN','China'),
    ('CX','Christmas Island'),
    ('CC','Cocos (Keeling) Islands'),
    ('CO','Colombia'),
    ('KM','Comoros'),
    ('CG','Congo'),
    ('CD','Congo, Democratic Republic of the'),
    ('CK','Cook Islands'),
    ('CR','Costa Rica'),
    ('CI','Côte d\'Ivoire'),
    ('HR','Croatia'),
    ('CU','Cuba'),
    ('CW','Curaçao'),
    ('CY','Cyprus'),
    ('CZ','Czechia'),
    ('DK','Denmark'),
    ('DJ','Djibouti'),
    ('DM','Dominica'),
    ('DO','Dominican Republic'),
    ('EC','Ecuador'),
    ('EG','Egypt'),
    ('SV','El Salvador'),
    ('GQ','Equatorial Guinea'),
    ('ER','Eritrea'),
    ('EE','Estonia'),
    ('SZ','Eswatini'),
    ('ET','Ethiopia'),
    ('FK','Falkland Islands (Malvinas)'),
    ('FO','Faroe Islands'),
    ('FJ','Fiji'),
    ('FI','Finland'),
    ('FR','France'),
    ('GF','French Guiana'),
    ('PF','French Polynesia'),
    ('TF','French Southern Territories'),
    ('GA','Gabon'),
    ('GM','Gambia'),
    ('GE','Georgia'),
    ('DE','Germany'),
    ('GH','Ghana'),
    ('GI','Gibraltar'),
    ('GR','Greece'),
    ('GL','Greenland'),
    ('GD','Grenada'),
    ('GP','Guadeloupe'),
    ('GU','Guam'),
    ('GT','Guatemala'),
    ('GG','Guernsey'),
    ('GN','Guinea'),
    ('GW','Guinea-Bissau'),
    ('GY','Guyana'),
    ('HT','Haiti'),
    ('HM','Heard Island and McDonald Islands'),
    ('VA','Holy See'),
    ('HN','Honduras'),
    ('HK','Hong Kong'),
    ('HU','Hungary'),
    ('IS','Iceland'),
    ('IN','India'),
    ('ID','Indonesia'),
    ('IR','Iran (Islamic Republic of)'),
    ('IQ','Iraq'),
    ('IE','Ireland'),
    ('IM','Isle of Man'),
    ('IL','Israel'),
    ('IT','Italy'),
    ('JM','Jamaica'),
    ('JP','Japan'),
    ('JE','Jersey'),
    ('JO','Jordan'),
    ('KZ','Kazakhstan'),
    ('KE','Kenya'),
    ('KI','Kiribati'),
    ('KP','Korea (Democratic People\'s Republic of)'),
    ('KR','Korea, Republic of'),
    ('KW','Kuwait'),
    ('KG','Kyrgyzstan'),
    ('LA','Lao People\'s Democratic Republic'),
    ('LV','Latvia'),
    ('LB','Lebanon'),
    ('LS','Lesotho'),
    ('LR','Liberia'),
    ('LY','Libya'),
    ('LI','Liechtenstein'),
    ('LT','Lithuania'),
    ('LU','Luxembourg'),
    ('MO','Macao'),
    ('MK','Macedonia, the former Yugoslav Republic of'),
    ('MG','Madagascar'),
    ('MW','Malawi'),
    ('MY','Malaysia'),
    ('MV','Maldives'),
    ('ML','Mali'),
    ('MT','Malta'),
    ('MH','Marshall Islands'),
    ('MQ','Martinique'),
    ('MR','Mauritania'),
    ('MU','Mauritius'),
    ('YT','Mayotte'),
    ('MX','Mexico'),
    ('FM','Micronesia (Federated States of)'),
    ('MD','Moldova, Republic of'),
    ('MC','Monaco'),
    ('MN','Mongolia'),
    ('ME','Montenegro'),
    ('MS','Montserrat'),
    ('MA','Morocco'),
    ('MZ','Mozambique'),
    ('MM','Myanmar'),
    ('NA','Namibia'),
    ('NR','Nauru'),
    ('NP','Nepal'),
    ('NL','Netherlands'),
    ('NC','New Caledonia'),
    ('NZ','New Zealand'),
    ('NI','Nicaragua'),
    ('NE','Niger'),
    ('NG','Nigeria'),
    ('NU','Niue'),
    ('NF','Norfolk Island'),
    ('MP','Northern Mariana Islands'),
    ('NO','Norway'),
    ('OM','Oman'),
    ('PK','Pakistan'),
    ('PW','Palau'),
    ('PS','Palestine, State of'),
    ('PA','Panama'),
    ('PG','Papua New Guinea'),
    ('PY','Paraguay'),
    ('PE','Peru'),
    ('PH','Philippines'),
    ('PN','Pitcairn'),
    ('PL','Poland'),
    ('PT','Portugal'),
    ('PR','Puerto Rico'),
    ('QA','Qatar'),
    ('RE','Réunion'),
    ('RO','Romania'),
    ('RU','Russian Federation'),
    ('RW','Rwanda'),
    ('BL','Saint Barthélemy'),
    ('SH','Saint Helena, Ascension and Tristan da Cunha'),
    ('KN','Saint Kitts and Nevis'),
    ('LC','Saint Lucia'),
    ('MF','Saint Martin (French part)'),
    ('PM','Saint Pierre and Miquelon'),
    ('VC','Saint Vincent and the Grenadines'),
    ('WS','Samoa'),
    ('SM','San Marino'),
    ('ST','Sao Tome and Principe'),
    ('SA','Saudi Arabia'),
    ('SN','Senegal'),
    ('RS','Serbia'),
    ('SC','Seychelles'),
    ('SL','Sierra Leone'),
    ('SG','Singapore'),
    ('SX','Sint Maarten (Dutch part)'),
    ('SK','Slovakia'),
    ('SI','Slovenia'),
    ('SB','Solomon Islands'),
    ('SO','Somalia'),
    ('ZA','South Africa'),
    ('GS','South Georgia and the South Sandwich Islands'),
    ('SS','South Sudan'),
    ('ES','Spain'),
    ('LK','Sri Lanka'),
    ('SD','Sudan'),
    ('SR','Suriname'),
    ('SJ','Svalbard and Jan Mayen'),
    ('SE','Sweden'),
    ('CH','Switzerland'),
    ('SY','Syrian Arab Republic'),
    ('TW','Taiwan, Province of China[a]'),
    ('TJ','Tajikistan'),
    ('TZ','Tanzania, United Republic of'),
    ('TH','Thailand'),
    ('TL','Timor-Leste'),
    ('TG','Togo'),
    ('TK','Tokelau'),
    ('TO','Tonga'),
    ('TT','Trinidad and Tobago'),
    ('TN','Tunisia'),
    ('TR','Turkey'),
    ('TM','Turkmenistan'),
    ('TC','Turks and Caicos Islands'),
    ('TV','Tuvalu'),
    ('UG','Uganda'),
    ('UA','Ukraine'),
    ('AE','United Arab Emirates'),
    ('GB','United Kingdom of Great Britain and Northern Ireland'),
    ('US','United States of America'),
    ('UM','United States Minor Outlying Islands'),
    ('UY','Uruguay'),
    ('UZ','Uzbekistan'),
    ('VU','Vanuatu'),
    ('VE','Venezuela (Bolivarian Republic of)'),
    ('VN','Viet Nam'),
    ('VG','Virgin Islands (British)'),
    ('VI','Virgin Islands (U.S.)'),
    ('WF','Wallis and Futuna'),
    ('EH','Western Sahara'),
    ('YE','Yemen'),
    ('ZM','Zambia'),
    ('ZW','Zimbabwe'),
]